### ISSUE TITLE
Redundant piece of code

### ISSUE THREAD

**Issue by rickgcv** [redhat-sap/sap-hana-hsr#3]
The backup destination for HANA is set in `global.ini` (default is $DIR_INSTANCE/backup/data) or specified in variable `hsr_backup_directory`. For that reason, IMHO this piece of code in `/templates/hsr_create_backup.sh.j2` is not needed as it just creates (if it does not exist) and changes the ownership of a directory that will not be used. 

``` if [ ! -d {{ item.value.hsr_backup_directory }} ]; then
 mkdir -p {{ item.value.hsr_backup_directory }}
 chown {{ item.value.hana_sid }}adm {{ item.value.hsr_backup_directory }}
fi
chown {{ item.value.hana_sid|lower }}adm {{ item.value.hsr_backup_directory }} ```

The backup will be  done to the default destination in `global.ini` or to directory specified in `hsr_backup_directory` that has already been created in `/tasks/hsr.yml`:

```
- name: create backup-directory
  file:
    path: "{{ item.value.hsr_backup_directory }}"
    state: directory
  with_dict: "{{ hsr }}"```

**Comment by makentenza** [comment]
Solved by #5
