### ISSUE TITLE
Failed to register the second node to hsr due to the 2nd site not stopped

### ISSUE THREAD

**Issue by mones84** [redhat-sap/sap-hana-hsr#8]
The following error shows while running the playbook: 

TASK [redhat_sap.sap_hana_hsr : Ensure HANA instance is stopped in the secondary node] **************************************************************************************
Tuesday 09 June 2020  20:16:19 +0530 (0:00:01.960)       0:14:37.043 ********** 
skipping: [saphana01]
changed: [saphana02]

TASK [redhat_sap.sap_hana_hsr : Register secondary node to HANA System Replication] *****************************************************************************************
Tuesday 09 June 2020  20:16:19 +0530 (0:00:00.681)       0:14:37.724 ********** 
skipping: [saphana01]
fatal: [saphana02]: FAILED! => {"changed": true, "cmd": "source /usr/sap/RHT/home/.sapenv.sh && /usr/sap/RHT/HDB01/exe/hdbnsutil -sr_register --name=DC2 --remoteHost=saphana01 --remoteInstance=01 --replicationMode=sync --operationMode=logreplay\n", "delta": "0:00:01.116768", "end": "2020-06-09 10:46:21.417939", "msg": "non-zero return code", "rc": 128, "start": "2020-06-09 10:46:20.301171", "stderr": "", "stderr_lines": [], "stdout": "adding site ...\nsystem must be shut down before it can be registered as secondary site. To register an online system please use the '--online' parameter; \nfailed. trace file nameserver_saphana02.00000.000.trc may contain more error details.", "stdout_lines": ["adding site ...", "system must be shut down before it can be registered as secondary site. To register an online system please use the '--online' parameter; ", "failed. trace file nameserver_saphana02.00000.000.trc may contain more error details."]}

--------------

I ran the role again, and the SAP Hana System Replications looks fine. 

To solve the issue, is it doable to add some time buffer to let the shutdown complete? 

BR./Edward

**Comment by makentenza** [comment]
@mones84 just for clarification, you run the playbook, it failed with the above error, then (without doing any change) you run the playbook again and it worked fine?

**Comment by mones84** [comment]
> @mones84 just for clarification, you run the playbook, it failed with the above error, then (without doing any change) you run the playbook again and it worked fine?

Hi Macros, 

Yes, exactly. The issue can be reproduced. 
I can share my environment if needed. 

Best Regards
Edward

**Comment by makentenza** [comment]
Solved by #9
